name: CI/CD Pipeline for Wisecow

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow when a pull request is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code in the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker for building images

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.coderiya }}  # Your Docker Hub username
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Your Docker Hub password (stored securely in GitHub Secrets)

    - name: Build Docker image
      run: |
        docker build -t coderiya/wisecow:latest .  # Build the Docker image

    - name: Push Docker image to Docker Hub
      run: |
        docker push coderiya/wisecow:latest  # Push the image to Docker Hub

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1  # Set up kubectl to interact with Kubernetes

    - name: Configure kubectl
      run: |
        kubectl config set-cluster my-cluster --server=https://https://127.0.0.1:32771  # Set your Kubernetes cluster API
        kubectl config set-credentials my-user --token=${{ secrets.bootstrap-token-dvv2zp }}  # Kubernetes token stored in GitHub Secrets
        kubectl config set-context my-context --cluster=my-cluster --user=my-user
        kubectl config use-context my-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml  # Deploy the updated application to Kubernetes